In [1]:
from google.colab import drive
drive.mount('/content/drive')
# drive.mount("/content/drive", force_remount=True)

Mounted at /content/drive


# Download my repo

In [ ]:
%cd /content/drive/MyDrive/Colab_Notebooks/SJSU/IAS/Final_Project/
!git clone https://github.com/georgevalan/PVKD.git  # clone
%cd PVKD

# Install dependencies

In [3]:
# Import all dependencies
!pip install torch
!pip install strictyaml
!pip install tqdm
!pip install numba
!pip install Cython
!pip install torch-scatter -f https://data.pyg.org/whl/torch-2.1.0+cu118.html
!pip install spconv-cu118

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.9/123.9 kB 2.7 MB/s eta 0:00:00
Looking in links: https://data.pyg.org/whl/torch-2.1.0+cu118.html
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 64.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.9/75.9 MB 22.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.5/71.5 kB 11.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.7/227.7 kB 28.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.3/88.3 kB 13.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.5/25.5 MB 8.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 307.2/307.2 kB 39.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 111.6/111.6 kB 16.3 MB/s eta 0:00:00
  Created wheel for fire: filename=fire-0.5.0-py2.py3-none-any.whl size=116934 sha256=3c0697ebacd547eeed3f8eed6250b689f1f1fca3c3809ea10c98bfacb47ad320
  Store

# Datasetup & File transfers

I used the following script for moving around dataset. If you have already figured it out, you make ship this section

In [ ]:
# !cp -r /content/drive/MyDrive/Colab_Notebooks/SJSU/datasets/semantic_kitti/sequences/20/ /content/drive/MyDrive/Colab_Notebooks/SJSU/datasets/semantic_kitti_dry_run_less_data/sequences/

In [ ]:
# !rm -r /content/drive/MyDrive/Colab_Notebooks/SJSU/datasets/semantic_kitti_dry_run_less_data/sequences/

In [ ]:
# import shutil, errno

# def copyanything(src, dst):
#     try:
#         shutil.copytree(src, dst)
#     except OSError as exc: # python >2.5
#         if exc.errno in (errno.ENOTDIR, errno.EINVAL):
#             shutil.copy(src, dst)
#         else: raise

# copyanything('/content/drive/MyDrive/Colab_Notebooks/SJSU/datasets/semantic_kitti/sequences/00/', '/content/drive/MyDrive/Colab_Notebooks/SJSU/datasets/semantic_kitti_dry_run_less_data/sequences/00/')
# copyanything('/content/drive/MyDrive/Colab_Notebooks/SJSU/datasets/semantic_kitti/sequences/20/', '/content/drive/MyDrive/Colab_Notebooks/SJSU/datasets/semantic_kitti_dry_run_less_data/sequences/20/')

In [ ]:
# !apt-get install tree
# !tree /content/drive/MyDrive/Colab_Notebooks/SJSU/datasets/semantic_kitti/sequences/ --filelimit 25
# # !tree /content/drive/MyDrive/Colab_Notebooks/SJSU/datasets/semantic_kitti_dry_run_less_data/sequences/ --filelimit 25

# Run GC and setup

This training is a very memory intensive operation. Run GC at 65% capacity.

In [ ]:
!export 'PYTORCH_CUDA_ALLOC_CONF=garbage_collection_threshold:0.65'

import torch
torch.cuda.empty_cache()

import gc
gc.collect()

0

# Train the teacher model

Set

```
model_to_train: ""
```
in semantickitti.yaml.

In [ ]:
!CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Colab_Notebooks/SJSU/IAS/Final_Project/PVKD/train_cyl_sem.py

/content/drive/MyDrive/Colab_Notebooks/SJSU/IAS/Final_Project/PVKD/train_cyl_sem.py
Namespace(config_path='/content/drive/MyDrive/Colab_Notebooks/SJSU/IAS/Final_Project/PVKD/config/semantickitti.yaml')
[480 360  32]
data_path ->  /content/drive/MyDrive/Colab_Notebooks/SJSU/datasets/semantic_kitti/sequences
train_imageset ->  train
  0% 0/551 [00:00<?, ?it/s]epoch 0 iter     0, loss: 4.025

100% 551/551 [04:55<00:00,  2.57it/s]
***** epoch 0, loss: 1.1810470819473267 *****

Validation per class iou: 
car : 40.96%
bicycle : 0.00%
motorcycle : nan%
truck : 0.00%
bus : 1.07%
person : 0.00%
bicyclist : nan%
motorcyclist : nan%
road : 62.08%
parking : 0.00%
sidewalk : 0.00%
other-ground : 0.00%
building : 0.22%
fence : 33.59%
vegetation : 61.60%
trunk : 2.52%
terrain : 32.19%
pole : 12.15%
traffic-sign : 0.71%
Current val miou is 15.443 while the best val miou is 15.443
Current val loss is 3.233
100% 551/551 [07:02<00:00,  1.31it/s]
 81% 449/551 [03:44<00:53,  1.92it/s]epoch 1 iter   449, lo

# Train the Student model without KD

Set

```
model_to_train: "student"
```
in semantickitti.yaml.


In [ ]:
!CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Colab_Notebooks/SJSU/IAS/Final_Project/PVKD/train_cyl_sem.py

/content/drive/MyDrive/Colab_Notebooks/SJSU/IAS/Final_Project/PVKD/train_cyl_sem.py
Namespace(config_path='/content/drive/MyDrive/Colab_Notebooks/SJSU/IAS/Final_Project/PVKD/config/semantickitti.yaml')
[480 360  32]
[480 360  32]
data_path ->  /content/drive/MyDrive/Colab_Notebooks/SJSU/datasets/semantic_kitti/sequences
train_imageset ->  train
  0% 0/551 [00:00<?, ?it/s]epoch 0 iter     0, loss: 3.983

100% 551/551 [05:29<00:00,  2.58it/s]
***** epoch 0, loss: 1.239574666140084 *****

Validation per class iou: 
car : 43.70%
bicycle : 0.00%
motorcycle : nan%
truck : 0.00%
bus : 1.17%
person : 0.00%
bicyclist : nan%
motorcyclist : 0.00%
road : 59.51%
parking : 0.00%
sidewalk : 0.00%
other-ground : 0.00%
building : 0.09%
fence : 24.62%
vegetation : 57.58%
trunk : 1.13%
terrain : 31.84%
pole : 26.55%
traffic-sign : 1.59%
Current val miou is 14.575 while the best val miou is 14.575
Current val loss is 3.415
100% 551/551 [09:16<00:00,  1.01s/it]
 81% 449/551 [03:42<00:49,  2.07it/s]epoch 1 

# Training with KD

Set

```
model_to_train: "student"
```
in semantickitti.yaml.

In [ ]:
!CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Colab_Notebooks/SJSU/IAS/Final_Project/PVKD/train_student_model_cyl_sem_KD.py

/content/drive/MyDrive/Colab_Notebooks/SJSU/IAS/Final_Project/PVKD/train_student_model_cyl_sem_KD.py
Namespace(config_path='/content/drive/MyDrive/Colab_Notebooks/SJSU/IAS/Final_Project/PVKD/config/semantickitti.yaml')
[480 360  32]
matched parameter sets: 274, and no matched: 0
[480 360  32]
data_path ->  /content/drive/MyDrive/Colab_Notebooks/SJSU/datasets/semantic_kitti/sequences
train_imageset ->  train
  0% 0/551 [00:00<?, ?it/s]epoch 0 iter     0, loss: 12.346

100% 551/551 [06:18<00:00,  1.95it/s]
***** epoch 0, loss: 10.187430598125701 *****

Validation per class iou: 
car : 35.29%
bicycle : 0.00%
motorcycle : nan%
truck : 0.00%
bus : 1.07%
person : 0.00%
bicyclist : nan%
motorcyclist : nan%
road : 61.13%
parking : 0.00%
sidewalk : 0.00%
other-ground : 0.00%
building : 0.12%
fence : 26.88%
vegetation : 54.52%
trunk : 2.26%
terrain : 33.91%
pole : 6.13%
traffic-sign : 6.50%
Current val miou is 14.237 while the best val miou is 14.237
Current val loss is 3.277
100% 551/551 [08:22

# Testing the Models

After running training for all these models, run the below script to run tests. This runs the predicted labels which can later be used to compare with the original labels used the semanticKitti development kit.

In [4]:
!CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Colab_Notebooks/SJSU/IAS/Final_Project/PVKD/test_cyl_sem_tta.py

/content/drive/MyDrive/Colab_Notebooks/SJSU/IAS/Final_Project/PVKD/test_cyl_sem_tta.py
Namespace(config_path='/content/drive/MyDrive/Colab_Notebooks/SJSU/IAS/Final_Project/PVKD/config/semantickitti.yaml')
[480 360  32]
matched parameter sets: 267, and no matched: 0
data_path ->  /content/drive/MyDrive/Colab_Notebooks/SJSU/datasets/semantic_kitti/sequences
train_imageset ->  train
********************************************************************************
Generate predictions for test split
********************************************************************************
100% 271/271 [05:03<00:00,  1.12s/it]
Predicted test labels are saved in /content/drive/MyDrive/Colab_Notebooks/SJSU/IAS/Final_Project/PVKD/out_cyl/test. Need to be shifted to original label format before submitting to the Competition website.
Remapping script can be found in semantic-kitti-api.
